version: '3'
#networks:
#  my-network:
#    external:
#      name: net_byfn
volumes:
  prometheus_data: {}
services:

  ##############
  # MONITORING #
  ##############

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

#    networks:
#      - my-network

  nodeexporter:
    container_name: nodeexporter
    image: prom/node-exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
#    networks:
#      - my-network

  grafana:
    container_name: grafana
    image:   grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana:/var/lib/grafana
      - ./grafana/conf:/usr/share/grafana/conf
#    networks:
#      - my-network

  pushGateway:
    image: prom/pushgateway
    container_name: pushGateway
    ports:
      - 9091:9091
#    networks:
#      - my-network

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    restart: always
#    networks:
#      - my-network

  ###############
  # MQTT BROKER #
  ###############

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
#    networks:
#      - my-network


