#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Fabric
version: "1.0"
mutual-tls: true

caliper:
    blockchain: fabric
    command:
        start: docker-compose -p caliper up -d;sleep 5s
        end: docker-compose -p caliper down;rm -rf /tmp/hfc-*;
clients:
    User1:
        client:
            organization: Org1
            credentialStore:
                path: /tmp/hfc-kvs/org1
                cryptoStore:
                    path: /tmp/hfc-cvs/org1
            clientPrivateKey:
                path: ./examples/first-network/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/bdaad768ecc9fa4d7e7e185a0989d29d2c776ab6490c594c7a0b0b41abc9db50_sk
            clientSignedCert:
                path: ./examples/first-network/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem

    User2:
        client:
            organization: Org2
            credentialStore:
                path: /tmp/hfc-kvs/org2
                cryptoStore:
                    path: /tmp/hfc-cvs/org2
            clientPrivateKey:
                path: ./examples/first-network/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/be11e255cf1a4fd4e55f8d2c007837fc4000f0831f7a6fc34dbadba53b9d70ac_sk
            clientSignedCert:
                path: ./examples/first-network/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/User1@org2.example.com-cert.pem

channels:
    mychannel:
        created: true
        orderers:
        - orderer.example.com
        peers:
            peer0.org1.example.com:
                eventSource: true
            peer0.org2.example.com:
                eventSource: true
        chaincodes:
            -   id: mycc
                contractID: mycc
                version: v1.0
                language: golang

organizations:
    Org1:
        mspid: Org1MSP
        peers:
        - peer0.org1.example.com
        adminPrivateKey:
            path: ./examples/first-network/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/eba6e45f424fe55c992a29d3478696535bb867fddc909d6ad64abea07a275292_sk
        signedCert:
            path: ./examples/first-network/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

    Org2:
        mspid: Org2MSP
        peers:
            - peer0.org2.example.com
        adminPrivateKey:
            path: ./examples/first-network/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/c1d452eb7894dfa70e66deb3789a4e8c05d0653ba29ef26dce5150c2e8d8da30_sk
        signedCert:
            path: ./examples/first-network/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem

orderers:
    orderer.example.com:
        url: grpcs://localhost:7050
        grpcOptions:
            ssl-target-name-override: orderer.example.com
        tlsCACerts:
            path: ./examples/first-network/crypto-config/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem

peers:
    peer0.org1.example.com:
        url: grpcs://localhost:7051
        grpcOptions:
            ssl-target-name-override: peer0.org1.example.com
            grpc.keepalive_time_ms: 600000
        tlsCACerts:
            path: ./examples/first-network/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

    peer0.org2.example.com:
        url: grpcs://localhost:9051
        grpcOptions:
            ssl-target-name-override: peer0.org2.example.com
            grpc.keepalive_time_ms: 600000
        tlsCACerts:
            path: ./examples/first-network/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

