global:
  scrape_interval:     1s

scrape_configs:
  - job_name: prometheus
    honor_labels: true # Retain labels, as within PushGateway use
    static_configs:
      - targets: ['prometheus:9090','pushGateway:9091','127.0.0.1:8443','127.0.0.1:9443']
        labels:
          instance: prometheus

  - job_name: cadvisor
    scrape_interval: 1s
    static_configs:
      - targets: ['127.0.0.1:8080']
        labels:
          instance: cadvisor

  - job_name: nodeexporter
    static_configs:
      - targets: ['127.0.0.1:9100']
        labels:
          instance: nodeexporter

