global:
  scrape_interval:     1s

scrape_configs:
  - job_name: prometheus
    honor_labels: true # Retain labels, as within PushGateway use
    static_configs:
      - targets: ['10.122.137.29:9090','10.122.137.29:9091','10.122.137.30:8443','10.122.137.30:10443']
        labels:
          instance: prometheus

  - job_name: cadvisor
    scrape_interval: 1s
    static_configs:
      - targets: ['10.122.137.30:8080']
        labels:
          instance: cadvisor

  - job_name: nodeexporter
    static_configs:
      - targets: ['10.122.137.30:9100']
        labels:
          instance: nodeexporter

